### PR TITLE
Full header length may be wrong when writing dbf file

### PR DESCRIPTION
**Pull request by yirrilo**
Hello,

Hope you feel good. 

Here is a request to update the actual version provided on maven central (thanks for that). 

I tried to open a dbf file with jdbf and observed that was working pretty well, but, when I decided to write the file, the full header lenght was not the same. The original dbf file had a bigger header than the written one. Unfortunately, jdbf did not update the value when dealing with the new file.

The result is that jdbf wasn't able to read the written dbf file because of the wrong header size. 

Here is a fix to calculate the good size when the header's array is built.

Best regards.

### CODE REVIEW

**Comment by spyhunter99** [comment]
Whoa awesome. I'll check it out, maybe write up a unit test, then merge it and cut another version. Thanks!

**Comment by spyhunter99** [comment]
do you by chance have an example that reproduces the problem?

**Comment by yirrilo** [comment]
Unfortunately, I can't provide the original dbf file and haven't a tool able to reproduce it, but I'll try to find out a way to reproduce that. I'll keep you in touch !

**Comment by yirrilo** [comment]
Hi there, 

Here is an update. What do You think @spyhunter99 ?

Best regards.

**Comment by spyhunter99** [comment]
awesome thanks. fix version will be 2.2.1

**Pull request merged**
